version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./build/package/cmd/Dockerfile
    privileged: true
  frontend:
    build:
      context: .
      dockerfile: ./build/package/web/Dockerfile